engagement:
    groupings:
        totals: 
            group_by: 
                - tweet.id
                - engagement.type
        daily_counts:
            group_by:
                - tweet.id
                - engagement.type
                - engagement.day

    engagement_types:
        - impressions
        - engagements
        - favorites
        - replies
        - retweets
        - url_clicks
        - hashtag_clicks
        - media_clicks
        - app_opens
        - email_tweet
        - user_follows
        - user_profile_clicks
        - video_views

